---
distribution: bullseye
ignore:
  temporary:
    PKG_NAME:
      version: "VERSION_STRING"
      reason: "see #XXXX"
    firmware-sof:
      version: 2.2.6-1
      reason: "will be fixed indirectly soon enough via #19888"
    cryptsetup:
      version: 2:2.6.1-4~deb12u1
      reason: "We install a backport of this version for Bullseye for #19728, no need to upgrade to the version from Bookworm"
  general:
    - tor
    - live-boot
